// Tous les accès DOM importants sont regroupés ici.
// Si un id ou une classe change dans le HTML, il suffit
// généralement de corriger ce fichier au lieu de chercher partout.
window.AppDom = {
    loginOverlay: document.getElementById('login-overlay'),
    loginForm: document.getElementById('login-form'),
    loginPassword: document.getElementById('admin-password'),
    loginError: document.getElementById('login-error'),
    alertBox: document.getElementById('custom-alert'),
    confirmDialog: document.getElementById('custom-confirm'),
    confirmCancel: document.getElementById('btn-confirm-annuler'),
    confirmDelete: document.getElementById('btn-confirm-oui'),
    editSacrementModal: document.getElementById('edit-sacrement-modal'),
    editSacrementForm: document.getElementById('edit-sacrement-form'),
    editSacrementClose: document.getElementById('edit-sacrement-close'),
    editSacrementCancel: document.getElementById('edit-sacrement-cancel'),
    editMariageModal: document.getElementById('edit-mariage-modal'),
    editMariageForm: document.getElementById('edit-mariage-form'),
    editMariageClose: document.getElementById('edit-mariage-close'),
    editMariageCancel: document.getElementById('edit-mariage-cancel'),
    mariageForm: document.getElementById('mariage-form'),
    sacrementForm: document.getElementById('sacrement-form'),
    searchInput: document.getElementById('searchInput'),
    resultsBody: document.querySelector('#resultsTable tbody'),
    resultsPager: document.getElementById('resultsPager'),
    resultsPrevPage: document.getElementById('resultsPrevPage'),
    resultsNextPage: document.getElementById('resultsNextPage'),
    resultsPageLabel: document.getElementById('resultsPageLabel'),
    archivesTable: document.getElementById('archivesTable'),
    archivesBody: document.querySelector('#archivesTable tbody'),
    archivesPager: document.getElementById('archivesPager'),
    archivesPrevPage: document.getElementById('archivesPrevPage'),
    archivesNextPage: document.getElementById('archivesNextPage'),
    archivesPageLabel: document.getElementById('archivesPageLabel'),
    archivesExportCsv: document.getElementById('archivesExportCsv'),
    navButtons: Array.from(document.querySelectorAll('[data-section-target]')),
    sections: Array.from(document.querySelectorAll('.content-section')),
    dashboardCards: Array.from(document.querySelectorAll('[data-filter-type]')),
    dashboardActions: Array.from(document.querySelectorAll('[data-dashboard-target]'))
};
